spring:
  application:
        name: ATM-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/digital-wallet
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      springframework:
        web: DEBUG
